# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: joao-alm <joao-alm@student.42luxembourg    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/27 10:51:30 by bpiovano          #+#    #+#              #
#    Updated: 2024/07/28 09:36:14 by joao-alm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SOURCES	= main.c ft_atoi.c count.c convert.c print.c dick.c
OBJECTS	= ${SOURCES:.c=.o}
INCLUDES	= cfiles
NAME	= rush-02
CC	= cc
RM	= rm -f
CFLAGS	= -Wall -Wextra -Werror

.c.o:
	${CC} ${CFLAGS} -c $< -o ${<:.c=.o} -I ${INCLUDES}

${NAME}:	${OBJECTS}
			gcc -o ${NAME} ${OBJECTS} ${CFLAGS}

all: ${NAME}

clean:
	${RM} ${OBJECTS}

fclean: clean
	${RM} ${NAME}

re: fclean all

norm :
	norminette -R CheckForbiddenSourceHeader */*.[ch]

.PHONY: all clean fclean re .c.o norm
